language: clojure
lein: 2.9.3
matrix:
  include:
    - jdk: openjdk13
services:
  - docker
after_success:
  - lein with-profile +test cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json