language: clojure
matrix:
  include:
    - jdk: openjdk12
sudo: true
services:
  - docker
after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json