name: check

on: [ push ]

jobs:
  clojure:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      - name: Run tests
        run: clojure -X:test:run-tests